// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMWOBzXQOa1G1rCW5sZITUr-Z4uHXQcU4',
    appId: '1:87062363095:web:app_id_here',
    messagingSenderId: '87062363095',
    projectId: 'bookmyspot-c8bdb',
    authDomain: 'bookmyspot-c8bdb.firebaseapp.com',
    storageBucket: 'bookmyspot-c8bdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMWOBzXQOa1G1rCW5sZITUr-Z4uHXQcU4',
    appId: '1:87062363095:android:dfc8f26f5ac5d0ec9ce992',
    messagingSenderId: '87062363095',
    projectId: 'bookmyspot-c8bdb',
    storageBucket: 'bookmyspot-c8bdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMWOBzXQOa1G1rCW5sZITUr-Z4uHXQcU4',
    appId: '1:87062363095:ios:dfc8f26f5ac5d0ec9ce992',
    messagingSenderId: '87062363095',
    projectId: 'bookmyspot-c8bdb',
    storageBucket: 'bookmyspot-c8bdb.appspot.com',
    iosBundleId: 'com.bms.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMWOBzXQOa1G1rCW5sZITUr-Z4uHXQcU4',
    appId: '1:87062363095:ios:dfc8f26f5ac5d0ec9ce992',
    messagingSenderId: '87062363095',
    projectId: 'bookmyspot-c8bdb',
    storageBucket: 'bookmyspot-c8bdb.appspot.com',
    iosBundleId: 'com.bms.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMWOBzXQOa1G1rCW5sZITUr-Z4uHXQcU4',
    appId: '1:87062363095:web:app_id_here',
    messagingSenderId: '87062363095',
    projectId: 'bookmyspot-c8bdb',
    authDomain: 'bookmyspot-c8bdb.firebaseapp.com',
    storageBucket: 'bookmyspot-c8bdb.appspot.com',
  );
}
